### ISSUE TITLE
Newest version from Enerdy API Tick 1.22 errors upon boot.

### ISSUE THREAD

**Issue by TeeriaLLC** [MarioE/TeleportRequest#1]
[11/20/15 14:11:46] [Server API] Warning: Plugin "Teleport" has had an unhandled exception thrown by one of its GameInitialize handlers: 
System.NullReferenceException: Object reference not set to an instance of an object.
  at TeleportRequest.TeleportRequest.OnInitialize(EventArgs e)
  at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

**Comment by TeeriaLLC** [comment]
@enerdy

**Comment by AxisKriel** [comment]
Why would you open an issue for my fork on this repo?

**Comment by AxisKriel** [comment]
@TeeriaLLC Downloaded my fork's version from the `bin` folder along with the latest TShock release from GitHub Releases and got no error at all. Doesn't seem to be an issue with vanilla TShock and just TeleportRequest (along with the default binaries) in the `ServerPlugins` folder, and we do not provide support for modified versions of TShock.
![pre](https://dl.dropboxusercontent.com/u/31979270/screenshots/Terraria_2_Electric_Boogaloo_2015-11-22_00-28-36.png)
![post](https://dl.dropboxusercontent.com/u/31979270/screenshots/08_%40_0.0.0.07777_%28TShock_for_Terraria_v4.3.11.0%29_2015-11-22_00-28-46.png)
